/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.awt.Image;
import java.io.IOException;
import java.lang.System.Logger;
import java.lang.System.Logger.Level;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Duc
 */
    public class frmChinh extends javax.swing.JFrame {
    private pnlkhachhang  pnlkhachhang;
    private GUI_SanPham  GUI_SanPham;
    private GUI_NhanVien  GUI_NhanVien;
    private GUI_ThongKe  GUI_ThongKe;
        private GUI_KhachHang  GUI_KhachHang;
    /**
     * Creates new form frmChinh
     */
    public frmChinh() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlnen = new javax.swing.JPanel();
        pnlnenmenu = new javax.swing.JPanel();
        btnbanhang = new javax.swing.JButton();
        btnsanpham = new javax.swing.JButton();
        btndonhang = new javax.swing.JButton();
        btnkhachhang = new javax.swing.JButton();
        btnhanghoa = new javax.swing.JButton();
        btntragop = new javax.swing.JButton();
        btnthongke = new javax.swing.JButton();
        btnwebsite = new javax.swing.JButton();
        pnlnenlogo = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lbltieude = new javax.swing.JLabel();
        pnlnendangxuat2 = new javax.swing.JPanel();
        lbldangxuat2 = new javax.swing.JLabel();
        btntongquan = new javax.swing.JButton();
        pnlnennoidung = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        pnlnoidung = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlnen.setBackground(new java.awt.Color(0, 102, 102));

        pnlnenmenu.setBackground(new java.awt.Color(0, 102, 102));

        btnbanhang.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnbanhang.setText("BÁN HÀNG");
        btnbanhang.setBorder(null);
        btnbanhang.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnbanhang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnbanhangMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnbanhangMouseExited(evt);
            }
        });
        btnbanhang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbanhangActionPerformed(evt);
            }
        });

        btnsanpham.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnsanpham.setText("SẢN PHẨM");
        btnsanpham.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnsanpham.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnsanphamMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnsanphamMouseExited(evt);
            }
        });
        btnsanpham.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsanphamActionPerformed(evt);
            }
        });

        btndonhang.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btndonhang.setText(" ĐƠN HÀNG");
        btndonhang.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btndonhang.setPreferredSize(new java.awt.Dimension(107, 27));
        btndonhang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btndonhangMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btndonhangMouseExited(evt);
            }
        });
        btndonhang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndonhangActionPerformed(evt);
            }
        });

        btnkhachhang.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnkhachhang.setText("     KHÁCH HÀNG");
        btnkhachhang.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnkhachhang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnkhachhangMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnkhachhangMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnkhachhangMouseExited(evt);
            }
        });
        btnkhachhang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnkhachhangActionPerformed(evt);
            }
        });

        btnhanghoa.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnhanghoa.setText("HÀNG HÓA");
        btnhanghoa.setToolTipText("");
        btnhanghoa.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnhanghoa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnhanghoaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnhanghoaMouseExited(evt);
            }
        });

        btntragop.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btntragop.setText("NHÂN VIÊN");
        btntragop.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btntragop.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btntragopMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btntragopMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btntragopMouseExited(evt);
            }
        });
        btntragop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntragopActionPerformed(evt);
            }
        });

        btnthongke.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnthongke.setText("THỐNG KÊ ");
        btnthongke.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnthongke.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnthongkeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnthongkeMouseExited(evt);
            }
        });
        btnthongke.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnthongkeActionPerformed(evt);
            }
        });

        btnwebsite.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnwebsite.setText("WEBSITE   ");
        btnwebsite.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnwebsite.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnwebsiteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnwebsiteMouseExited(evt);
            }
        });
        btnwebsite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnwebsiteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlnenmenuLayout = new javax.swing.GroupLayout(pnlnenmenu);
        pnlnenmenu.setLayout(pnlnenmenuLayout);
        pnlnenmenuLayout.setHorizontalGroup(
            pnlnenmenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlnenmenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnbanhang, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(btnsanpham, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btndonhang, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnkhachhang, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnhanghoa, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btntragop, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnthongke, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnwebsite, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlnenmenuLayout.setVerticalGroup(
            pnlnenmenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlnenmenuLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(pnlnenmenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnbanhang, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnsanpham, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btndonhang, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnkhachhang, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnhanghoa, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btntragop, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnthongke, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnwebsite, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlnenlogo.setBackground(new java.awt.Color(33, 36, 51));

        jPanel6.setBackground(new java.awt.Color(0, 99, 104));
        jPanel6.setDoubleBuffered(false);
        jPanel6.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel6MouseDragged(evt);
            }
        });
        jPanel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel6MousePressed(evt);
            }
        });

        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });

        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });

        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });

        lbltieude.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        lbltieude.setForeground(new java.awt.Color(255, 255, 255));
        lbltieude.setText("TRANG CHỦ");

        pnlnendangxuat2.setBackground(new java.awt.Color(0, 102, 102));
        pnlnendangxuat2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        pnlnendangxuat2.setPreferredSize(new java.awt.Dimension(200, 50));

        lbldangxuat2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lbldangxuat2.setForeground(new java.awt.Color(255, 255, 255));
        lbldangxuat2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbldangxuat2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbldangxuat2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbldangxuat2lbldangxuatMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbldangxuat2lbldangxuatMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pnlnendangxuat2Layout = new javax.swing.GroupLayout(pnlnendangxuat2);
        pnlnendangxuat2.setLayout(pnlnendangxuat2Layout);
        pnlnendangxuat2Layout.setHorizontalGroup(
            pnlnendangxuat2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbldangxuat2, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
        );
        pnlnendangxuat2Layout.setVerticalGroup(
            pnlnendangxuat2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbldangxuat2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
        );

        btntongquan.setBackground(new java.awt.Color(153, 204, 255));
        btntongquan.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btntongquan.setForeground(new java.awt.Color(0, 153, 153));
        btntongquan.setToolTipText("");
        btntongquan.setAutoscrolls(true);
        btntongquan.setBorder(null);
        btntongquan.setBorderPainted(false);
        btntongquan.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btntongquan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btntongquanMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btntongquanMouseExited(evt);
            }
        });
        btntongquan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntongquanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addComponent(pnlnendangxuat2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btntongquan, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(481, 481, 481)
                .addComponent(lbltieude)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addGap(2, 2, 2)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(lbltieude, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(pnlnendangxuat2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE))
                    .addComponent(btntongquan, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout pnlnenlogoLayout = new javax.swing.GroupLayout(pnlnenlogo);
        pnlnenlogo.setLayout(pnlnenlogoLayout);
        pnlnenlogoLayout.setHorizontalGroup(
            pnlnenlogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlnenlogoLayout.setVerticalGroup(
            pnlnenlogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlnenlogoLayout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pnlnennoidung.setBackground(new java.awt.Color(225, 226, 226));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new java.awt.BorderLayout());

        pnlnoidung.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout pnlnoidungLayout = new javax.swing.GroupLayout(pnlnoidung);
        pnlnoidung.setLayout(pnlnoidungLayout);
        pnlnoidungLayout.setHorizontalGroup(
            pnlnoidungLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1453, Short.MAX_VALUE)
        );
        pnlnoidungLayout.setVerticalGroup(
            pnlnoidungLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 703, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout pnlnennoidungLayout = new javax.swing.GroupLayout(pnlnennoidung);
        pnlnennoidung.setLayout(pnlnennoidungLayout);
        pnlnennoidungLayout.setHorizontalGroup(
            pnlnennoidungLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnlnennoidungLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(pnlnoidung, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlnennoidungLayout.setVerticalGroup(
            pnlnennoidungLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnlnennoidungLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlnennoidungLayout.createSequentialGroup()
                    .addComponent(pnlnoidung, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout pnlnenLayout = new javax.swing.GroupLayout(pnlnen);
        pnlnen.setLayout(pnlnenLayout);
        pnlnenLayout.setHorizontalGroup(
            pnlnenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlnennoidung, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlnenlogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlnenmenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlnenLayout.setVerticalGroup(
            pnlnenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlnenLayout.createSequentialGroup()
                .addComponent(pnlnenlogo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlnenmenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlnennoidung, javax.swing.GroupLayout.PREFERRED_SIZE, 698, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlnen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(pnlnen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnbanhangMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnbanhangMouseEntered
        Image photo2 = new ImageIcon(this.getClass().getResource("/IMAGE/banhang2.jpg")).getImage();
        btnbanhang.setIcon(new ImageIcon(photo2));
    }//GEN-LAST:event_btnbanhangMouseEntered

    private void btnbanhangMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnbanhangMouseExited
        Image photo2 = new ImageIcon(this.getClass().getResource("/IMAGE/banhang.jpg")).getImage();
        btnbanhang.setIcon(new ImageIcon(photo2));
    }//GEN-LAST:event_btnbanhangMouseExited

    private void btnbanhangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbanhangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnbanhangActionPerformed

    private void btnsanphamMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnsanphamMouseEntered
        Image photo2 = new ImageIcon(this.getClass().getResource("/IMAGE/sanpham2.jpg")).getImage();
        btnsanpham.setIcon(new ImageIcon(photo2));
    }//GEN-LAST:event_btnsanphamMouseEntered

    private void btnsanphamMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnsanphamMouseExited
        Image photo2 = new ImageIcon(this.getClass().getResource("/IMAGE/sanpham.jpg")).getImage();
        btnsanpham.setIcon(new ImageIcon(photo2));
    }//GEN-LAST:event_btnsanphamMouseExited

    private void btndonhangMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btndonhangMouseEntered
        Image photo2 = new ImageIcon(this.getClass().getResource("/IMAGE/donhang2.jpg")).getImage();
        btndonhang.setIcon(new ImageIcon(photo2));
    }//GEN-LAST:event_btndonhangMouseEntered

    private void btndonhangMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btndonhangMouseExited
        Image photo2 = new ImageIcon(this.getClass().getResource("/IMAGE/donhang.jpg")).getImage();
        btndonhang.setIcon(new ImageIcon(photo2));
    }//GEN-LAST:event_btndonhangMouseExited

    private void btndonhangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndonhangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btndonhangActionPerformed

    private void btnkhachhangMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnkhachhangMouseEntered
        // TODO add your handling code here:
        Image photo2 = new ImageIcon(this.getClass().getResource("/IMAGE/khachhang2.jpg")).getImage();
        btnkhachhang.setIcon(new ImageIcon(photo2));
    }//GEN-LAST:event_btnkhachhangMouseEntered

    private void btnkhachhangMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnkhachhangMouseExited
        Image photo2 = new ImageIcon(this.getClass().getResource("/IMAGE/khachhang.jpg")).getImage();
        btnkhachhang.setIcon(new ImageIcon(photo2));
    }//GEN-LAST:event_btnkhachhangMouseExited

    private void btnkhachhangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnkhachhangActionPerformed
        // TODO add your handling code here:
//        this.dispose();     //Hủy form Đăng nhập
                GUI_KhachHang = new GUI_KhachHang();     
                GUI_KhachHang.setVisible(true); 
    }//GEN-LAST:event_btnkhachhangActionPerformed

    private void btnhanghoaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnhanghoaMouseEntered
        Image photo2 = new ImageIcon(this.getClass().getResource("/IMAGE/hanghoa2.jpg")).getImage();
        btnhanghoa.setIcon(new ImageIcon(photo2));
    }//GEN-LAST:event_btnhanghoaMouseEntered

    private void btnhanghoaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnhanghoaMouseExited
        Image photo2 = new ImageIcon(this.getClass().getResource("/IMAGE/hanghoa.jpg")).getImage();
        btnhanghoa.setIcon(new ImageIcon(photo2));
    }//GEN-LAST:event_btnhanghoaMouseExited

    private void btntragopMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btntragopMouseClicked
        pnlnhanvien nhanvien=new pnlnhanvien();
        nhanvien.setVisible(true);
    }//GEN-LAST:event_btntragopMouseClicked

    private void btntragopMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btntragopMouseEntered
        Image photo2 = new ImageIcon(this.getClass().getResource("/IMAGE/tragop2.jpg")).getImage();
        btntragop.setIcon(new ImageIcon(photo2));
    }//GEN-LAST:event_btntragopMouseEntered

    private void btntragopMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btntragopMouseExited
        Image photo2 = new ImageIcon(this.getClass().getResource("/IMAGE/tragop.jpg")).getImage();
        btntragop.setIcon(new ImageIcon(photo2));
    }//GEN-LAST:event_btntragopMouseExited

    private void btntragopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntragopActionPerformed
        // TODO add your handling code here:
//        this.dispose();     //Hủy form Đăng nhập
                GUI_NhanVien = new GUI_NhanVien();     
                GUI_NhanVien.setVisible(true); 
    }//GEN-LAST:event_btntragopActionPerformed

    private void btnthongkeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnthongkeMouseEntered
        Image photo2 = new ImageIcon(this.getClass().getResource("/IMAGE/thongke2.jpg")).getImage();
        btnthongke.setIcon(new ImageIcon(photo2));
    }//GEN-LAST:event_btnthongkeMouseEntered

    private void btnthongkeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnthongkeMouseExited
        Image photo2 = new ImageIcon(this.getClass().getResource("/IMAGE/thongke.jpg")).getImage();
        btnthongke.setIcon(new ImageIcon(photo2));
    }//GEN-LAST:event_btnthongkeMouseExited

    private void btnwebsiteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnwebsiteMouseEntered
        // TODO add your handling code here:
        Image photo2 = new ImageIcon(this.getClass().getResource("/IMAGE/web2.jpg")).getImage();
        btnwebsite.setIcon(new ImageIcon(photo2));
    }//GEN-LAST:event_btnwebsiteMouseEntered

    private void btnwebsiteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnwebsiteMouseExited
        // TODO add your handling code here:
        Image photo2 = new ImageIcon(this.getClass().getResource("/IMAGE/web.jpg")).getImage();
        btnwebsite.setIcon(new ImageIcon(photo2));
    }//GEN-LAST:event_btnwebsiteMouseExited

    private void btnwebsiteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnwebsiteActionPerformed
        // TODO add your handling code here:

        String url = "https://camtapp.herokuapp.com/";
        try {
            java.awt.Desktop.getDesktop().browse(java.net.URI.create(url));
        } catch (IOException ex) {
            Logger.getLogger(frmmain.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnwebsiteActionPerformed

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked

    }//GEN-LAST:event_jLabel4MouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        int result = JOptionPane.showConfirmDialog(this, "Bạn có chắc chắn muốn thoát khỏi phần mềm?", "Xác nhận thoát", JOptionPane.OK_CANCEL_OPTION);
        if (result == JOptionPane.OK_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_jLabel5MouseClicked

    private void lbldangxuat2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbldangxuat2MouseClicked

    }//GEN-LAST:event_lbldangxuat2MouseClicked

    private void lbldangxuat2lbldangxuatMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbldangxuat2lbldangxuatMouseEntered
        // TODO add your handling code here:
        setcolorbutton(pnlnendangxuat2);
    }//GEN-LAST:event_lbldangxuat2lbldangxuatMouseEntered

    private void lbldangxuat2lbldangxuatMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbldangxuat2lbldangxuatMouseExited
        // TODO add your handling code here:
        resetcolorbutton(pnlnendangxuat2);
    }//GEN-LAST:event_lbldangxuat2lbldangxuatMouseExited

    private void btntongquanMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btntongquanMouseEntered
        Image photo2 = new ImageIcon(this.getClass().getResource("/IMAGE/home2.jpg")).getImage();
        btntongquan.setIcon(new ImageIcon(photo2));
    }//GEN-LAST:event_btntongquanMouseEntered

    private void btntongquanMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btntongquanMouseExited
        Image photo2 = new ImageIcon(this.getClass().getResource("/IMAGE/home.jpg")).getImage();
        btntongquan.setIcon(new ImageIcon(photo2));
    }//GEN-LAST:event_btntongquanMouseExited

    private void btntongquanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntongquanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btntongquanActionPerformed

    private void jPanel6MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel6MouseDragged

    }//GEN-LAST:event_jPanel6MouseDragged

    private void jPanel6MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel6MousePressed

    }//GEN-LAST:event_jPanel6MousePressed

    private void btnkhachhangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnkhachhangMouseClicked
        // TODO add your handling code here:
           this.dispose();     //Hủy form Đăng nhập
            pnlkhachhang pnlkhachhang = new pnlkhachhang(); //Tạo mới formChinh
           pnlkhachhang.setVisible(true);
    }//GEN-LAST:event_btnkhachhangMouseClicked

    private void btnsanphamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsanphamActionPerformed
        // TODO add your handling code here:
         // TODO add your handling code here:
//        this.dispose();     //Hủy form Đăng nhập
                GUI_SanPham = new GUI_SanPham();     
                GUI_SanPham.setVisible(true);
    }//GEN-LAST:event_btnsanphamActionPerformed

    private void btnthongkeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnthongkeActionPerformed
        // TODO add your handling code here:
//         this.dispose();     //Hủy form Đăng nhập
                GUI_ThongKe= new GUI_ThongKe();     
                GUI_ThongKe.setVisible(true);
    }//GEN-LAST:event_btnthongkeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmChinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmChinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmChinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmChinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmChinh().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnbanhang;
    private javax.swing.JButton btndonhang;
    private javax.swing.JButton btnhanghoa;
    private javax.swing.JButton btnkhachhang;
    private javax.swing.JButton btnsanpham;
    private javax.swing.JButton btnthongke;
    private javax.swing.JButton btntongquan;
    private javax.swing.JButton btntragop;
    private javax.swing.JButton btnwebsite;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JLabel lbldangxuat2;
    private javax.swing.JLabel lbltieude;
    private javax.swing.JPanel pnlnen;
    private javax.swing.JPanel pnlnendangxuat2;
    private javax.swing.JPanel pnlnenlogo;
    private javax.swing.JPanel pnlnenmenu;
    private javax.swing.JPanel pnlnennoidung;
    private javax.swing.JPanel pnlnoidung;
    // End of variables declaration//GEN-END:variables
}
