/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

/**
 *
 * @author Duc
 */
public class GUI_CHINH extends javax.swing.JFrame {

    /**
     * Creates new form GUI_CHINH
     */
    public GUI_CHINH() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlnenmenu1 = new javax.swing.JPanel();
        btnbanhang1 = new javax.swing.JButton();
        btnsanpham1 = new javax.swing.JButton();
        btndonhang1 = new javax.swing.JButton();
        btnkhachhang1 = new javax.swing.JButton();
        btnhanghoa1 = new javax.swing.JButton();
        btntragop1 = new javax.swing.JButton();
        btnthongke1 = new javax.swing.JButton();
        btnwebsite1 = new javax.swing.JButton();
        pnlnennoidung = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        pnlnoidung = new javax.swing.JPanel();
        pnlnenlogo = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lbltieude = new javax.swing.JLabel();
        pnlnendangxuat2 = new javax.swing.JPanel();
        lbldangxuat2 = new javax.swing.JLabel();
        btntongquan = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlnenmenu1.setBackground(new java.awt.Color(0, 102, 102));

        btnbanhang1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnbanhang1.setText("BÁN HÀNG");
        btnbanhang1.setBorder(null);
        btnbanhang1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnbanhang1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnbanhang1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnbanhang1MouseExited(evt);
            }
        });
        btnbanhang1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbanhang1ActionPerformed(evt);
            }
        });

        btnsanpham1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnsanpham1.setText("SẢN PHẨM");
        btnsanpham1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnsanpham1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnsanpham1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnsanpham1MouseExited(evt);
            }
        });
        btnsanpham1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsanpham1ActionPerformed(evt);
            }
        });

        btndonhang1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btndonhang1.setText(" ĐƠN HÀNG");
        btndonhang1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btndonhang1.setPreferredSize(new java.awt.Dimension(107, 27));
        btndonhang1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btndonhang1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btndonhang1MouseExited(evt);
            }
        });
        btndonhang1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndonhang1ActionPerformed(evt);
            }
        });

        btnkhachhang1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnkhachhang1.setText("     KHÁCH HÀNG");
        btnkhachhang1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnkhachhang1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnkhachhang1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnkhachhang1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnkhachhang1MouseExited(evt);
            }
        });
        btnkhachhang1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnkhachhang1ActionPerformed(evt);
            }
        });

        btnhanghoa1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnhanghoa1.setText("HÀNG HÓA");
        btnhanghoa1.setToolTipText("");
        btnhanghoa1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnhanghoa1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnhanghoa1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnhanghoa1MouseExited(evt);
            }
        });

        btntragop1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btntragop1.setText("NHÂN VIÊN");
        btntragop1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btntragop1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btntragop1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btntragop1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btntragop1MouseExited(evt);
            }
        });
        btntragop1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntragop1ActionPerformed(evt);
            }
        });

        btnthongke1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnthongke1.setText("THỐNG KÊ ");
        btnthongke1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnthongke1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnthongke1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnthongke1MouseExited(evt);
            }
        });
        btnthongke1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnthongke1ActionPerformed(evt);
            }
        });

        btnwebsite1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnwebsite1.setText("WEBSITE   ");
        btnwebsite1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnwebsite1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnwebsite1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnwebsite1MouseExited(evt);
            }
        });
        btnwebsite1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnwebsite1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlnenmenu1Layout = new javax.swing.GroupLayout(pnlnenmenu1);
        pnlnenmenu1.setLayout(pnlnenmenu1Layout);
        pnlnenmenu1Layout.setHorizontalGroup(
            pnlnenmenu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlnenmenu1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnbanhang1, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(btnsanpham1, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btndonhang1, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnkhachhang1, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnhanghoa1, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btntragop1, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnthongke1, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnwebsite1, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlnenmenu1Layout.setVerticalGroup(
            pnlnenmenu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlnenmenu1Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(pnlnenmenu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnbanhang1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnsanpham1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btndonhang1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnkhachhang1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnhanghoa1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btntragop1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnthongke1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnwebsite1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlnennoidung.setBackground(new java.awt.Color(225, 226, 226));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new java.awt.BorderLayout());

        pnlnoidung.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout pnlnoidungLayout = new javax.swing.GroupLayout(pnlnoidung);
        pnlnoidung.setLayout(pnlnoidungLayout);
        pnlnoidungLayout.setHorizontalGroup(
            pnlnoidungLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1453, Short.MAX_VALUE)
        );
        pnlnoidungLayout.setVerticalGroup(
            pnlnoidungLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 703, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout pnlnennoidungLayout = new javax.swing.GroupLayout(pnlnennoidung);
        pnlnennoidung.setLayout(pnlnennoidungLayout);
        pnlnennoidungLayout.setHorizontalGroup(
            pnlnennoidungLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnlnennoidungLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(pnlnoidung, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlnennoidungLayout.setVerticalGroup(
            pnlnennoidungLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnlnennoidungLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlnennoidungLayout.createSequentialGroup()
                    .addComponent(pnlnoidung, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pnlnenlogo.setBackground(new java.awt.Color(33, 36, 51));

        jPanel6.setBackground(new java.awt.Color(0, 99, 104));
        jPanel6.setDoubleBuffered(false);
        jPanel6.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel6MouseDragged(evt);
            }
        });
        jPanel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel6MousePressed(evt);
            }
        });

        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });

        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });

        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });

        lbltieude.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        lbltieude.setForeground(new java.awt.Color(255, 255, 255));
        lbltieude.setText("TRANG CHỦ");

        pnlnendangxuat2.setBackground(new java.awt.Color(0, 102, 102));
        pnlnendangxuat2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        pnlnendangxuat2.setPreferredSize(new java.awt.Dimension(200, 50));

        lbldangxuat2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lbldangxuat2.setForeground(new java.awt.Color(255, 255, 255));
        lbldangxuat2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbldangxuat2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbldangxuat2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbldangxuat2lbldangxuatMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbldangxuat2lbldangxuatMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pnlnendangxuat2Layout = new javax.swing.GroupLayout(pnlnendangxuat2);
        pnlnendangxuat2.setLayout(pnlnendangxuat2Layout);
        pnlnendangxuat2Layout.setHorizontalGroup(
            pnlnendangxuat2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbldangxuat2, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
        );
        pnlnendangxuat2Layout.setVerticalGroup(
            pnlnendangxuat2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbldangxuat2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
        );

        btntongquan.setBackground(new java.awt.Color(153, 204, 255));
        btntongquan.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btntongquan.setForeground(new java.awt.Color(0, 153, 153));
        btntongquan.setToolTipText("");
        btntongquan.setAutoscrolls(true);
        btntongquan.setBorder(null);
        btntongquan.setBorderPainted(false);
        btntongquan.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btntongquan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btntongquanMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btntongquanMouseExited(evt);
            }
        });
        btntongquan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntongquanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addComponent(pnlnendangxuat2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btntongquan, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(481, 481, 481)
                .addComponent(lbltieude)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addGap(2, 2, 2)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(lbltieude, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(pnlnendangxuat2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE))
                    .addComponent(btntongquan, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout pnlnenlogoLayout = new javax.swing.GroupLayout(pnlnenlogo);
        pnlnenlogo.setLayout(pnlnenlogoLayout);
        pnlnenlogoLayout.setHorizontalGroup(
            pnlnenlogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlnenlogoLayout.setVerticalGroup(
            pnlnenlogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlnenlogoLayout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlnennoidung, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlnenlogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlnenmenu1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlnenlogo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlnenmenu1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlnennoidung, javax.swing.GroupLayout.PREFERRED_SIZE, 698, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnbanhang1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnbanhang1MouseEntered
        Image photo2 = new ImageIcon(this.getClass().getResource("/IMAGE/banhang2.jpg")).getImage();
        btnbanhang.setIcon(new ImageIcon(photo2));
    }//GEN-LAST:event_btnbanhang1MouseEntered

    private void btnbanhang1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnbanhang1MouseExited
        Image photo2 = new ImageIcon(this.getClass().getResource("/IMAGE/banhang.jpg")).getImage();
        btnbanhang.setIcon(new ImageIcon(photo2));
    }//GEN-LAST:event_btnbanhang1MouseExited

    private void btnbanhang1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbanhang1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnbanhang1ActionPerformed

    private void btnsanpham1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnsanpham1MouseEntered
        Image photo2 = new ImageIcon(this.getClass().getResource("/IMAGE/sanpham2.jpg")).getImage();
        btnsanpham.setIcon(new ImageIcon(photo2));
    }//GEN-LAST:event_btnsanpham1MouseEntered

    private void btnsanpham1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnsanpham1MouseExited
        Image photo2 = new ImageIcon(this.getClass().getResource("/IMAGE/sanpham.jpg")).getImage();
        btnsanpham.setIcon(new ImageIcon(photo2));
    }//GEN-LAST:event_btnsanpham1MouseExited

    private void btnsanpham1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsanpham1ActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:
        //        this.dispose();     //Hủy form Đăng nhập
        GUI_SanPham = new GUI_SanPham();
        GUI_SanPham.setVisible(true);
    }//GEN-LAST:event_btnsanpham1ActionPerformed

    private void btndonhang1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btndonhang1MouseEntered
        Image photo2 = new ImageIcon(this.getClass().getResource("/IMAGE/donhang2.jpg")).getImage();
        btndonhang.setIcon(new ImageIcon(photo2));
    }//GEN-LAST:event_btndonhang1MouseEntered

    private void btndonhang1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btndonhang1MouseExited
        Image photo2 = new ImageIcon(this.getClass().getResource("/IMAGE/donhang.jpg")).getImage();
        btndonhang.setIcon(new ImageIcon(photo2));
    }//GEN-LAST:event_btndonhang1MouseExited

    private void btndonhang1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndonhang1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btndonhang1ActionPerformed

    private void btnkhachhang1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnkhachhang1MouseClicked
        // TODO add your handling code here:
        this.dispose();     //Hủy form Đăng nhập
        pnlkhachhang pnlkhachhang = new pnlkhachhang(); //Tạo mới formChinh
        pnlkhachhang.setVisible(true);
    }//GEN-LAST:event_btnkhachhang1MouseClicked

    private void btnkhachhang1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnkhachhang1MouseEntered
        // TODO add your handling code here:
        Image photo2 = new ImageIcon(this.getClass().getResource("/IMAGE/khachhang2.jpg")).getImage();
        btnkhachhang.setIcon(new ImageIcon(photo2));
    }//GEN-LAST:event_btnkhachhang1MouseEntered

    private void btnkhachhang1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnkhachhang1MouseExited
        Image photo2 = new ImageIcon(this.getClass().getResource("/IMAGE/khachhang.jpg")).getImage();
        btnkhachhang.setIcon(new ImageIcon(photo2));
    }//GEN-LAST:event_btnkhachhang1MouseExited

    private void btnkhachhang1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnkhachhang1ActionPerformed
        // TODO add your handling code here:
        //        this.dispose();     //Hủy form Đăng nhập
        GUI_KhachHang = new GUI_KhachHang();
        GUI_KhachHang.setVisible(true);
    }//GEN-LAST:event_btnkhachhang1ActionPerformed

    private void btnhanghoa1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnhanghoa1MouseEntered
        Image photo2 = new ImageIcon(this.getClass().getResource("/IMAGE/hanghoa2.jpg")).getImage();
        btnhanghoa.setIcon(new ImageIcon(photo2));
    }//GEN-LAST:event_btnhanghoa1MouseEntered

    private void btnhanghoa1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnhanghoa1MouseExited
        Image photo2 = new ImageIcon(this.getClass().getResource("/IMAGE/hanghoa.jpg")).getImage();
        btnhanghoa.setIcon(new ImageIcon(photo2));
    }//GEN-LAST:event_btnhanghoa1MouseExited

    private void btntragop1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btntragop1MouseClicked
        pnlnhanvien nhanvien=new pnlnhanvien();
        nhanvien.setVisible(true);
    }//GEN-LAST:event_btntragop1MouseClicked

    private void btntragop1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btntragop1MouseEntered
        Image photo2 = new ImageIcon(this.getClass().getResource("/IMAGE/tragop2.jpg")).getImage();
        btntragop.setIcon(new ImageIcon(photo2));
    }//GEN-LAST:event_btntragop1MouseEntered

    private void btntragop1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btntragop1MouseExited
        Image photo2 = new ImageIcon(this.getClass().getResource("/IMAGE/tragop.jpg")).getImage();
        btntragop.setIcon(new ImageIcon(photo2));
    }//GEN-LAST:event_btntragop1MouseExited

    private void btntragop1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntragop1ActionPerformed
        // TODO add your handling code here:
        //        this.dispose();     //Hủy form Đăng nhập
        GUI_NhanVien = new GUI_NhanVien();
        GUI_NhanVien.setVisible(true);
    }//GEN-LAST:event_btntragop1ActionPerformed

    private void btnthongke1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnthongke1MouseEntered
        Image photo2 = new ImageIcon(this.getClass().getResource("/IMAGE/thongke2.jpg")).getImage();
        btnthongke.setIcon(new ImageIcon(photo2));
    }//GEN-LAST:event_btnthongke1MouseEntered

    private void btnthongke1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnthongke1MouseExited
        Image photo2 = new ImageIcon(this.getClass().getResource("/IMAGE/thongke.jpg")).getImage();
        btnthongke.setIcon(new ImageIcon(photo2));
    }//GEN-LAST:event_btnthongke1MouseExited

    private void btnthongke1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnthongke1ActionPerformed
        // TODO add your handling code here:
        //         this.dispose();     //Hủy form Đăng nhập
        GUI_ThongKe= new GUI_ThongKe();
        GUI_ThongKe.setVisible(true);
    }//GEN-LAST:event_btnthongke1ActionPerformed

    private void btnwebsite1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnwebsite1MouseEntered
        // TODO add your handling code here:
        Image photo2 = new ImageIcon(this.getClass().getResource("/IMAGE/web2.jpg")).getImage();
        btnwebsite.setIcon(new ImageIcon(photo2));
    }//GEN-LAST:event_btnwebsite1MouseEntered

    private void btnwebsite1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnwebsite1MouseExited
        // TODO add your handling code here:
        Image photo2 = new ImageIcon(this.getClass().getResource("/IMAGE/web.jpg")).getImage();
        btnwebsite.setIcon(new ImageIcon(photo2));
    }//GEN-LAST:event_btnwebsite1MouseExited

    private void btnwebsite1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnwebsite1ActionPerformed
        // TODO add your handling code here:

        String url = "https://camtapp.herokuapp.com/";
        try {
            java.awt.Desktop.getDesktop().browse(java.net.URI.create(url));
        } catch (IOException ex) {
            Logger.getLogger(frmmain.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnwebsite1ActionPerformed

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked

    }//GEN-LAST:event_jLabel4MouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        int result = JOptionPane.showConfirmDialog(this, "Bạn có chắc chắn muốn thoát khỏi phần mềm?", "Xác nhận thoát", JOptionPane.OK_CANCEL_OPTION);
        if (result == JOptionPane.OK_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_jLabel5MouseClicked

    private void lbldangxuat2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbldangxuat2MouseClicked

    }//GEN-LAST:event_lbldangxuat2MouseClicked

    private void lbldangxuat2lbldangxuatMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbldangxuat2lbldangxuatMouseEntered
        // TODO add your handling code here:
        setcolorbutton(pnlnendangxuat2);
    }//GEN-LAST:event_lbldangxuat2lbldangxuatMouseEntered

    private void lbldangxuat2lbldangxuatMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbldangxuat2lbldangxuatMouseExited
        // TODO add your handling code here:
        resetcolorbutton(pnlnendangxuat2);
    }//GEN-LAST:event_lbldangxuat2lbldangxuatMouseExited

    private void btntongquanMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btntongquanMouseEntered
        Image photo2 = new ImageIcon(this.getClass().getResource("/IMAGE/home2.jpg")).getImage();
        btntongquan.setIcon(new ImageIcon(photo2));
    }//GEN-LAST:event_btntongquanMouseEntered

    private void btntongquanMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btntongquanMouseExited
        Image photo2 = new ImageIcon(this.getClass().getResource("/IMAGE/home.jpg")).getImage();
        btntongquan.setIcon(new ImageIcon(photo2));
    }//GEN-LAST:event_btntongquanMouseExited

    private void btntongquanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntongquanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btntongquanActionPerformed

    private void jPanel6MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel6MouseDragged

    }//GEN-LAST:event_jPanel6MouseDragged

    private void jPanel6MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel6MousePressed

    }//GEN-LAST:event_jPanel6MousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI_CHINH.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI_CHINH.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI_CHINH.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI_CHINH.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI_CHINH().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnbanhang;
    private javax.swing.JButton btnbanhang1;
    private javax.swing.JButton btndonhang;
    private javax.swing.JButton btndonhang1;
    private javax.swing.JButton btnhanghoa;
    private javax.swing.JButton btnhanghoa1;
    private javax.swing.JButton btnkhachhang;
    private javax.swing.JButton btnkhachhang1;
    private javax.swing.JButton btnsanpham;
    private javax.swing.JButton btnsanpham1;
    private javax.swing.JButton btnthongke;
    private javax.swing.JButton btnthongke1;
    private javax.swing.JButton btntongquan;
    private javax.swing.JButton btntragop;
    private javax.swing.JButton btntragop1;
    private javax.swing.JButton btnwebsite;
    private javax.swing.JButton btnwebsite1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JLabel lbldangxuat2;
    private javax.swing.JLabel lbltieude;
    private javax.swing.JPanel pnlnendangxuat2;
    private javax.swing.JPanel pnlnenlogo;
    private javax.swing.JPanel pnlnenmenu;
    private javax.swing.JPanel pnlnenmenu1;
    private javax.swing.JPanel pnlnennoidung;
    private javax.swing.JPanel pnlnoidung;
    // End of variables declaration//GEN-END:variables
}
